### ISSUE TITLE
TypeError: n.subarray is not a function (regression in v5.25) 

### ISSUE THREAD

**Issue by iamakulov** [statoscope/statoscope#202]
**Describe the bug**

Heya – thank you for maintaining Statoscope! Incredibly useful tool.

Since I upgraded to v5.25, Statoscope started crashing when loading the UI. The error reads like this:

```
statoscope-unnamed-187619ba9f701cb87367.html:78 Uncaught TypeError: n.subarray is not a function
    at Object.inflate (statoscope-unnamed-187619ba9f701cb87367.html:78:38851)
    at window.Pako.la.push (statoscope-unnamed-187619ba9f701cb87367.html:78:45733)
    at statoscope-unnamed-187619ba9f701cb87367.html:1299:28
    at Array.map (<anonymous>)
    at Object.parse (statoscope-unnamed-187619ba9f701cb87367.html:1290:43)
    at statoscope-unnamed-187619ba9f701cb87367.html:1327:24
```

The relevant line seems to be this (this is the only mention of `.subarray()` in the diff between v5.24 and v5.25):

https://github.com/statoscope/statoscope/blob/e5f168391f5fbd59cb065441986d57ad7d60cadf/packages/report-writer/src/utils.ts#L72

If you pause at the exception, you’ll notice `n` is defined, it just doesn’t have the `subarray` function (because it’s a regular array):

<img width="225" alt="Screenshot 2023-02-18 at 18 22 01" src="https://user-images.githubusercontent.com/2953267/219881047-f67c0987-490e-49b7-b974-dcafe0c1a90a.png">

**To Reproduce**

1. Run

   ```sh
   git clone git@github.com:appsmithorg/appsmith.git --depth 1
   cd appsmith/app/client
   cp .env.example .env
   yarn
   ```

2. Install Statoscope:

   ```sh
   yarn add @statoscope/webpack-plugin
   ```

3. Add Statoscope to `craco.common.config.js`:

   ```js
   const StatoscopeWebpackPlugin = require("@statoscope/webpack-plugin").default;
   
   module.exports = {
     // ...
     webpack: {
       // ...
       configure: {
         // ...
         plugins: [new StatoscopeWebpackPlugin({ statsOptions: { all: true }, open: "file" })],
       }
     }
   }
   ```

4. Build the app:

   ```sh
   yarn build
   ```
   
5. Observe how the report opens but hangs at “Parsing...”. Observe the above error in the JS console

**Expected behavior**
The report should load successfully.

**Screenshots**

<img width="1005" alt="Screenshot 2023-02-18 at 18 32 51" src="https://user-images.githubusercontent.com/2953267/219880018-1e8c07ba-a458-4f80-ba6e-9a93a1a7989f.png">

**Versions**:
 - Node (for non-browser bug): 
 - Browser (for browser-bug): 109.0.5414.119 (Official Build) (arm64) 
 - Webpack: 5.73.0
 - Statoscope: 5.25

**Comment by smelukov** [comment]
@iamakulov Thanks! Working on it

**Comment by smelukov** [comment]
@iamakulov there was several problems. I've fixed these
Published in 5.25.1
